In [1]:
import pandas as pd
import math
import itertools

In [2]:
df = pd.read_csv(r'C:\Users\Admin\Documents\School\UWL\Summer 2023\Capstone\US_Accidents_March23.csv')

In [3]:
dfUtah = df[df['State']=='UT']

In [4]:
dfUtah.describe(include='all')

,ID,Source,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
count,97079,97079,97079.000000,97079,97079,97079.000000,97079.000000,64234.000000,64234.000000,97079.000000,...,97079,97079,97079,97079,97079,97079,96677,96677,96677,96677
unique,97079,3,NaN,83304,85405,NaN,NaN,NaN,NaN,NaN,...,1,2,2,2,2,1,2,2,2,2
top,A-512511,Source1,NaN,2021-12-24 01:01:31,2020-12-31 04:00:00,NaN,NaN,NaN,NaN,NaN,...,False,False,False,False,False,False,Day,Day,Day,Day
freq,1,64234,NaN,23,15,NaN,NaN,NaN,NaN,NaN,...,97079,94680,95562,97077,82708,97079,65841,70959,76241,80597
mean,NaN,NaN,2.181914,NaN,NaN,40.385817,-111.891131,40.351619,-111.885894,0.779369,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,0.442441,NaN,NaN,0.948092,0.565894,0.980792,0.592316,2.473633,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN,36.999979,-114.043760,36.994231,-114.053065,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,2.000000,NaN,NaN,40.360734,-112.000225,40.328683,-112.003866,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,2.000000,NaN,NaN,40.664330,-111.905060,40.665625,-111.905140,0.076000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,2.000000,NaN,NaN,40.790744,-111.821729,40.771162,-111.806964,0.679000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,4.000000,NaN,NaN,41.999320,-109.044947,41.999320,-109.025227,156.529999,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
print(len(round(dfUtah['Start_Lat'],2).unique()))
print(len(round(dfUtah['Start_Lng'],2).unique()))

501
498

In [6]:
dfUtah['Geo_Region'] = round(dfUtah['Start_Lat'],1).replace(' ','').astype(str) + '_' + round(dfUtah['Start_Lng'],1).replace(' ','').astype(str)

C:\Users\Tony Anderson\AppData\Local\Temp\ipykernel_16856\2208745549.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfUtah['Geo_Region'] = round(dfUtah['Start_Lat'],1).replace(' ','').astype(str) + '_' + round(dfUtah['Start_Lng'],1).replace(' ','').astype(str)

In [7]:
print(dfUtah.columns)

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight', 'Geo_Region'],
      dtype='object')

In [17]:
regions = []
dataDict = {}

for i,j in dfUtah.iterrows():
    # Region
    lat1 = str(j['Start_Lat'])[0:4]
    lat2 = '1'
    try:
        if str(j['Start_Lat'])[4] in ['0','1']:
            lat2 = '1'
        elif str(j['Start_Lat'])[4] in ['2','3']:
            lat2 = '3'
        elif str(j['Start_Lat'])[4] in ['4','5']:
            lat2 = '5'
        elif str(j['Start_Lat'])[4] in ['6','7']:
            lat2 = '7'
        elif str(j['Start_Lat'])[4] in ['8','9']:
            lat2 = '9'
    except:
        lat2 = '1'
    latFull = lat1 + lat2
    lon1 = str(j['Start_Lng']).replace('-','')[0:5]
    lon2 = '1'
    try:
        if str(j['Start_Lng'])[5] in ['0','1']:
            lon2 = '1'
        elif str(j['Start_Lng'])[5] in ['2','3']:
            lon2 = '3'
        elif str(j['Start_Lng'])[5] in ['4','5']:
            lon2 = '5'
        elif str(j['Start_Lng'])[5] in ['6','7']:
            lon2 = '7'
        elif str(j['Start_Lng'])[5] in ['8','9']:
            lon2 = '9'
    except:
        lon2 = '1'
    lonFull = lon1 + lon2
    region = latFull + ',-' + lonFull
    
    #temperature
    tempF = ''
    if j['Temperature(F)']  <= 32:
        tempF = '<= 32'
    elif j['Temperature(F)'] < 80:
        tempF = '< 80'
    else:
        tempF = '80+'
    
    #dew point
    tempC = (j['Temperature(F)'] - 32) * (5/9)
    Td = tempC - ((100-j['Humidity(%)'])/5)
    dewPoint = ''
    if Td <= 55:
        dewPoint = 'dry'
    elif Td <= 65:
        dewPoint = 'moderate'
    else:
        dewPoint = 'humid'
        
    #pressure
    press = ''
    if j['Pressure(in)'] < 27.3:
        press = 'low'
    elif j['Pressure(in)'] <= 30:
        press = 'normal'
    else:
        press = 'high'
    
    #day/night
    dayNight = j['Sunrise_Sunset']
    
    #precipitation
    precip = ''
    if j['Precipitation(in)'] > 0:
        precip = 'True'
    else:
        precip = 'False'
        
    #traffic signal
    traffSig = j['Traffic_Signal']
    
    #roundabout
    roundA = j['Roundabout']
    
    #stop
    stop = j['Stop']
    
    #traffic final
    traffic = ''
    if str(j['Roundabout']) == 'True':
        traffic = 'True'
    elif str(j['Traffic_Signal']) == 'True':
        traffic = 'True'
    elif str(j['Stop']) == 'True':
        traffic = 'True'
    else:
        traffic = 'False'
    
    #severity
    severity = j['Severity']
    
    #temp
    tempList = [region, tempF, str(dayNight), str(precip)
                #, str(traffSig), str(roundA), str(stop)
                ,traffic]
    #tempList = [tempF,dewPoint]
    
    if region not in regions:
        regions.append(region)
        
    key = ';'.join(tempList)
    
    if key not in dataDict.keys():
        dataDict[key] = {'severity': severity, 'count': 1}
    else:
        dataDict[key]['severity'] += severity
        dataDict[key]['count'] += 1

In [18]:
temps = ['<= 32', '< 80', '80+']
dewPoints = ['dry','moderate','humid']
dayNights = ['Day','Night']
precipitations = ['True','False']
traffics = ['True','False']
combinations = [regions,temps,dayNights,precipitations,traffics]
#combinations = [regions,temps,dewPoints,dayNights,precipitations,traffics]
#combinations = [temps,dewPoints]
combos = list(itertools.product(*combinations))

for i in combos:
    text = ''
    for ii in i:
        if text == '':
            text = ii
        else:
            text = text + ';' + ii
    if text not in dataDict.keys():
        dataDict[text] = {'severity': 0, 'count': 0}
print(len(dataDict.keys()))

47650

In [21]:
finalRegionList = []
for i in dataDict.keys():
    tempList = i.split(';')
    region = tempList[0]
    regionSplit = region.split(',')
    lat = regionSplit[0]
    lon = regionSplit[1]
    tempF = tempList[1]
    #dewPoint = tempList[2]
    dayNight = tempList[2]
    precip = tempList[3]
    traffic = tempList[4]
    severity = dataDict[i]['severity']
    count = dataDict[i]['count']
    #temp = [region,lat,lon,tempF,dewPoint,dayNight,precip,traffic,severity,count]
    temp = [region,lat,lon,tempF,dayNight,precip,traffic,severity,count]
    finalRegionList.append(temp)
    
#finalRegionDf = pd.DataFrame(finalRegionList, columns = ['region','lat','lon','temperature','dewPoint','dayNight','precip','traffic','severity','cnt'])

finalRegionDf = pd.DataFrame(finalRegionList, columns = ['region','lat','lon','temperature','dayNight','precip','traffic','severity','cnt'])

print(finalRegionDf.head(5))

          region    lat      lon temperature dayNight precip traffic  \
0  40.79,-111.99  40.79  -111.99         80+      Day  False   False
1  41.79,-112.11  41.79  -112.11         80+      Day  False   False
2  40.29,-111.77  40.29  -111.77         80+      Day  False   False
3  38.53,-109.45  38.53  -109.45        < 80    Night  False   False
4  40.77,-111.89  40.77  -111.89         80+      Day  False    True

   severity  cnt
0       332  137
1        23   10
2        85   36
3        21    7
4        95   44

In [26]:
finalRegionDf['precip'].unique()

array(['False', 'True'], dtype=object)

In [27]:
finalRegionDf = finalRegionDf.sort_values('region')

finalRegionDf.to_csv('finalDatasetNew.csv', index=False)